### ISSUE TITLE
AccessViolation in SELA decoder

### ISSUE THREAD

**Issue by xer0times** [sahaRatul/sela#18]
The target crashed on an access violation at an address matching the source operand of the current instruction. This likely indicates a read access violation. here is the sanitizer output:

```
SimplE Lossless Audio Decoder
Copyright (c) 2015-2016. Ratul Saha
Released under MIT license

Input : crash/id:000004,sig:06,src:000004,op:flip1,pos:2138
Output : out.wav

Stream Information
------------------
Sample rate : 22050 Hz
Bits per sample : 16
Channels : 1(Monoaural)

Metadata
--------
No metadata found
[                         ]AddressSanitizer:DEADLYSIGNAL
=================================================================
==4257==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000526190 bp 0x7ffddc5c1060 sp 0x7ffddc5a4240 T0)
==4257==The signal is caused by a READ memory access.
==4257==Hint: address points to the zero page.
    #0 0x52618f in dqtz_ref_cof /home/xer0days/Service_test/sela-latest/core/lpc.c:279:13
    #1 0x516ea3 in main /home/xer0days/Service_test/sela-latest/core/decode.c:163:5
    #2 0x7f764bce182f in __libc_start_main /build/glibc-GKVZIf/glibc-2.23/csu/../csu/libc-start.c:291
    #3 0x41a188 in _start (/home/xer0days/Service_test/sela-latest/fuzzing_report/seladec/seladec+0x41a188)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/xer0days/Service_test/sela-latest/core/lpc.c:279:13 in dqtz_ref_cof
==4257==ABORTING
```
and some information in gdb :

```
<PEDA> p q_ref[i]+64
$22 = 0x80600d41
<PEDA> x/x *0x80600d41
Cannot access memory at address 0x80600d41
```

[id_000004,sig_06,src_000004,op_flip1,pos_2138.zip](https://github.com/sahaRatul/sela/files/2524301/id_000004.sig_06.src_000004.op_flip1.pos_2138.zip)
[id_000005,sig_06,src_000004,op_flip1,pos_4124.zip](https://github.com/sahaRatul/sela/files/2524302/id_000005.sig_06.src_000004.op_flip1.pos_4124.zip)
[id_000007,sig_06,src_000004,op_flip1,pos_9470.zip](https://github.com/sahaRatul/sela/files/2524303/id_000007.sig_06.src_000004.op_flip1.pos_9470.zip)

**Comment by sahaRatul** [comment]
Hey, if you are still there, the entire code has been rewritten from scratch and it should fix this issue. Feel free to recheck.
